#!/usr/bin/env bash
# Install nginx and  show a string "hello world" at the root

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
