#!/usr/bin/env bash
# Install nginx and  show a string "hello world" at the root

sudo apt update
sudo apt -y install nginx

echo "Hello World!" > index.html
sudo mv index.html /var/www/html

sudo service nginx start
