#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

# redirection
REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start

#Custom error page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
sudo service nginx restart
