#!/usr/bin/env bash
#Bash script to configure a brand new ubuntu server with Nginx
#Adds a custom Header

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
#redirection
REDIRECT="location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

#Custom Error page
sudo echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html
CUSTOM="error_page 404 /404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default

#Adding custom HTTP headers
HEADER="add_header X-Served-By $HOSTNAME;"
sudo sed -i "22i $HEADER" /etc/nginx/nginx.conf

sudo service nginx restart
