#!/usr/bin/env bash
# install and configure load balancer
FRONTEND="frontend Local_server\n\tbind *:80\n\tmode http\n\tdefault_backend my_web_servers"
BACKEND="backend my_web_servers\n\tmode http\n\tbalance roundrobin\n\tserver web-01 18.232.187.106:80 check\n\tserver web-02 18.206.13.226:80 check"


sudo apt-update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo sed -i "\$a $FRONTEND" /etc/haproxy/haproxy.cfg
sudo sed -i "\$a $BACKEND" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
