#!/usr/bin/env bash
#install and setup ufw firewall
#setup allows incoming traffic from ssh, https and http

sudo apt install ufw
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable 
