#!/usr/bin/env/ bash
# fix nginx to reduce vulnerablility and use least privilege

pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "li user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
