#!/usr/bin/env/ bash
# fix nginx to reduce vulnerablility and use least privilege
chmod 644 /etc/nginx/nginx.conf
sed -Ei "s/\s*#?*user .*/user nginx;/" /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx restart
